export const credits = [
    {  band: 'Paramore',
        album: 'forthcoming LP',
        label: 'Atlantic/Fueled By Ramen',
        year: 2017,
        role: 'Engineer'
    },
    {  band: 'Cherry Glazerr',
        album: 'Apocalipstick',
        label: 'Secretly Canadian',
        year: 2017,
        role: 'Producer, Engineer, Mixer',
        cover: 'cherryglazerr_apocalipstick.jpg'
    },
    {  band: 'Jimmy Eat World',
        album: 'forthcoming LP',
        label: 'RCA',
        year: 2017,
        role: 'Engineer',
        cover: 'jimmyeatworld_integrityblues.jpg'
    },
    {  band: 'The Naked and Famous',
        album: 'Simple Forms',
        label: 'KLS/Somewhat Damaged',
        year: 2016,
        role: 'Engineer',
        cover: 'tnaf_simpleforms.jpeg'
    },
    {  band: 'Ziggy Marley',
        album: 'Self-Titled',
        label: 'Tough Gong Worldwide',
        year: 2016,
        role: 'Mixer, Engineer',
        cover: 'ziggymarley_st.jpg'
    },
    {  band: 'M83',
        album: 'Junk',
        label: 'Mute',
        year: 2016,
        role: 'Mixer, Engineer',
        cover: 'm83_junk.jpg'
    },
    {  band: 'Bleached',
        album: 'Welcome The Worms',
        label: 'Dead Oceans',
        year: 2016,
        role: 'Producer, Engineer, Mixer',
        cover: 'bleached_welcometheworms.jpg'
    },
    {  band: 'Wild Belle',
        album: 'Dreamland',
        label: 'Columbia',
        year: 2016,
        role: 'Engineer, Guitar, Bass',
        cover: 'wildbelle_dreamland.jpg'
    },
    {  band: 'School of Seven Bells',
        album: 'SVIIB',
        label: 'Vagrant',
        year: 2016,
        role: 'Engineer',
        cover: 'sviib_sviib.jpg'
    },
    {  band: 'YACHT',
        album: 'I Thought the Future Would Be Cooler',
        label: 'Downtown',
        year: 2015,
        role: 'Engineer',
        cover: 'yacht_ittgwbc.jpg'
    },
    {  band: 'WATERS',
        album: 'What’s Real',
        label: 'Vagrant',
        year: 2015,
        role: 'Producer, Engineer, Mixer, Keys',
        cover: 'waters_whatsreal.jpg'
    },
    {  band: 'Young the Giant',
        album: 'Mind Over Matter',
        label: 'Atlantic/Fueled By Ramen',
        year: 2015,
        role: 'Engineer',
        cover: 'youngthegiant_mindovermatter.jpg'
    },
    {  band: 'The Colourist',
        album: 'Self-Titled',
        label: 'Universal/Republic',
        year: 2014,
        role: 'Producer, Engineer, Keys',
        cover: 'thecoloursist_st.jpg'
    },
    {  band: 'Tegan and Sara',
        album: 'Heartthrob',
        label: 'Warner',
        year: 2013,
        role: 'Engineer',
        cover: 'teganandsara_heartthrob.jpg'
    },
    {  band: 'Paramore',
        album: 'Self-Titled',
        label: 'Atlantic/Fueled By Ramen',
        year: 2013,
        role: 'Engineer, Percussion',
        cover: 'paramore_st.jpg'
    },
    {  band: 'Neon Trees',
        album: 'Picture Show',
        label: 'Mercury',
        year: 2012,
        role: 'Engineer, Percussion',
        cover: 'neontrees_pictureshow.jpg'
    },
    {  band: 'Neon Trees',
        album: 'Habits',
        label: 'Mercury',
        year: 2010,
        role: 'Engineer, Mixer',
        cover: 'neontrees_habits.jpg'
    },

]
